To-Do List - collaborative project
uryelah/Microverse-604-todo-list pull request #1
Opened 2020-02-26 13:22 UTC by uryelah

**Hi Tse!** 👋 

Can you please check our Todo List project and provide feedback?

**Summary:**
- applied functional programming (factories and modules) 
-  todo item contains title, description, due date,  priority, time, tags, checklist and button to add them;
- projects and todo lists are separated;
- application logic is separated to DOM manipulation;
- on the user interface is possible to see all projects, all todos in each project;
- todos and projects can be edited and deleted;
- todos can be completed, incompleted and expired;
- tasks can be marked as completed;
- todo can be set by day and by time;
- users can see the next task;
- users can see tasks ordered by date or by priority.Thank you in advance for your time.

Kind regards,
**Sarah & Thaís 🦄**

2020-02-27 06:48 UTC, Oghenebrume50 requested changes
**STATUS: CHANGES REQUIRED**

Hi Team everything looks really good in the code but for some reason, I could not test this the buttons do not click 
And please delete console.log from the code base :slightly_smiling_face: 

**RAPHAEL NORIODE** :sunglasses:

2020-02-27 12:01 UTC, uryelah commented
We couldn't find any `console.log` in the todolist branch, in which file and line did you find one?

2020-02-27 12:16 UTC, uryelah commented
The `console.log`s where at an older bundle. Re-bundled app and added instalation info to the readme file.

2020-02-28 01:27 UTC, mcrd25 approved these changes
# Changes Approved 💪 🎊 

Hey @uryelah! Hey @thsvr! 👋 

Great job with the project! You've met all the requirements.
I like the effort.

Maybe you can work on some of your more wonky features, but really this is a really creative and clearly thoughtful project you did here!

***If you have any questions, now or in the future, do not hesitate to contact me on social media, email or on slack and I will be glad to chat with you.***

*Happy coding 😄,*
**[--Maya](https://github.com/mcrd25)**
[GitHub](https://github.com/mcrd25) [Twitter](https://twitter.com/mcrd25) [linkedin](https://www.linkedin.com/in/mayadouglas/) [GitLab](https://gitlab.com/mcrd25)

2020-02-28 01:27 UTC, mcrd25 commented on README.md
>  <!-- CONTACT -->
[OPTIONAL]
Don't forget to add Live Demo Link to README

2020-02-28 19:40 UTC, merged